### ISSUE TITLE
bug install

### ISSUE THREAD

**Issue by RyzenK8** [santos-jp7/yettz#1]
Microsoft Windows [version 10.0.18363.836]
(c) 2019 Microsoft Corporation. Tous droits réservés.

C:\Users\Utiliser\Desktop\yettz-master>npm start

> yettz@3.0.2 start C:\Users\Utiliser\Desktop\yettz-master
> node index.js

(node:19868) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
    at WebSocketConnection.<anonymous> (C:\Users\Utiliser\Desktop\yettz-master\node_modules\discord.js\src\client\ClientManager.js:48:41)
    at Object.onceWrapper (events.js:422:26)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.onClose (C:\Users\Utiliser\Desktop\yettz-master\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:390:10)
    at WebSocket.onClose (C:\Users\Utiliser\Desktop\yettz-master\node_modules\ws\lib\event-target.js:124:16)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.emitClose (C:\Users\Utiliser\Desktop\yettz-master\node_modules\ws\lib\websocket.js:191:10)
    at TLSSocket.socketOnClose (C:\Users\Utiliser\Desktop\yettz-master\node_modules\ws\lib\websocket.js:850:15)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
(node:19868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:19868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

C:\Users\Utiliser\Desktop\yettz-master>

**Comment by santos-jp7** [comment]
Você configurou seu arquivo .env certinho? Isso é por falha em seu token.

**Comment by RyzenK8** [comment]
DEV_ID={seu id de usuario} Where can it be found ?

TOKEN={o token de seu bot}
PREFIX={o prefixo para utilização dos comandos}

**Comment by santos-jp7** [comment]
- DEV_ID = Your Discord user id
- TOKEN = Your bot token
- PREFIX = Prefix for commands

To get your user id it is necessary to put your discord in developer mode -> https://www.youtube.com/watch?v=KAOfKtqE0X0

**Comment by RyzenK8** [comment]
The problem persists

**Comment by santos-jp7** [comment]
Your problem is caused by TOKEN -> https://discord.com/developers/applications

![token location](https://user-images.githubusercontent.com/59297843/83313930-9f974200-a1ee-11ea-87ab-8db7ba3221f6.png)

**Comment by RyzenK8** [comment]
It was here I got my token to integrate them into the code and I start it makes mistakes

**Comment by santos-jp7** [comment]
Confirm to me that your .env file is following this example:
![env](https://user-images.githubusercontent.com/59297843/83330388-ede72800-a264-11ea-9134-e086769f6350.png)

**Comment by RyzenK8** [comment]
Thanks it works but a question how to update 
![IMG_20200530_200728](https://user-images.githubusercontent.com/34812693/83336145-522fd900-a2b1-11ea-898e-cbeeba5bff4a.jpg)

**Comment by santos-jp7** [comment]
`git clone https://github.com/santos-jp7/yettz`

You only need to leave the .env file

**Comment by RyzenK8** [comment]
Thank you
