### ISSUE TITLE
Update API discord

### ISSUE THREAD

**Issue by RyzenK8** [santos-jp7/yettz#3]
Hello, this is to report a problem: simply discord announcing the change of API you can send the fixes on deposit.

My bot is based on your LTS (Long-term support) version project for stability and security.

Here is the announcement in detail by discord : https://pastebin.com/dvRV59gk

Have a good day ^^

**Comment by santos-jp7** [comment]
Good afternoon, I apologize for not having responded earlier. These changes are not affecting the bot. But any divergence, I will make the change.

**Comment by RyzenK8** [comment]
I look forward to your long term project.

you have the possibility to carry out translations in international level in English.

Thanks for the answers.
